;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-semi&comma
        indent-for-tab-command
        ))

(setq mc/cmds-to-run-once
      '(
        ignore
        lsp-ui-doc--handle-mouse-movement
        ))
