(deftheme nates-sweet-theme
  "Created 2016-12-16.")

(custom-theme-set-faces
 'nates-sweet-theme
 '(font-lock-builtin-face ((t (:foreground "#808080"))))
 '(region ((t (:background "#804000" :foreground "#e0e2e4"))))
 '(highlight ((t (:background "#3c414c"))))
 '(hl-line ((t (:background "#2f393c"))))
 '(fringe ((t (:background "#232323" :foreground "#cfbfad"))))
 '(cursor ((t (:background "#626262"))))
 '(show-paren-match ((t nil)))
 '(isearch ((t (:bold t :foreground "#616161" :background "#e2e2e5"))))
 '(mode-line ((t (:foreground "#b2b2b2" :background "#293134" :box nil))))
 '(mode-line-inactive ((t (:foreground "#949494" :background "#293134" :box nil))))
 '(mode-line-buffer-id ((t (:foreground "#898989" :background "#293134"))))
 '(minibuffer-prompt ((t (:bold t :foreground "#708090"))))
 '(font-lock-comment-face ((t (:foreground "#7d8c93"))))
 '(font-lock-negation-char-face ((t (:foreground "#e8e2b7"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#7d8c93"))))
 '(font-lock-constant-face ((t (:foreground "#A082bd"))))
 '(font-lock-doc-face ((t (:foreground "#7d8c93"))))
 '(font-lock-function-name-face ((t (:foreground "#e0e2e4"))))
 '(font-lock-keyword-face ((t (:bold t :foreground "#93c763"))))
 '(font-lock-preprocessor-face ((t (:foreground "#a082bd"))))
 '(font-lock-string-face ((t (:foreground "#ec7600"))))
 '(font-lock-type-face ((t (:foreground "#93c763"))))
 '(font-lock-variable-name-face ((t (:foreground "#678cb1"))))
 '(font-lock-warning-face ((t (:foreground "#ff6523"))))
 '(link ((t (:foreground "#678cb1"))))
 '(trailing-whitespace ((t :foreground nil :background "#3f4c51")))
 '(default ((t (:background "#293134" :foreground "#e0e2e4")))))

(provide-theme 'nates-sweet-theme)
